-- EXECUTE ESTE COMANDO NO SQL EDITOR DO SUPABASE
-- PARA ADICIONAR O CAMPO DE SENHA NA TABELA DE USUÁRIOS

ALTER TABLE perfis ADD COLUMN IF NOT EXISTS senha TEXT;

-- Garante que o RLS não esteja bloqueando a nova coluna
ALTER TABLE perfis DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE perfis TO anon;
GRANT ALL ON TABLE perfis TO authenticated;
